/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

/* *****************************************************************************************************
This file is part of the CaT-Z software. 
2020, Porto, Portugal

Authors: Ana Gerós (anafgeros@ineb.up.pt), Paulo Aguiar (pauloaguiar@ineb.up.pt)

If you use this software, please acknowledge our work published in: 
“Gerós, A., Magalhães, A. &  Aguiar, P. Improved 3D tracking and automatic classification of rodent’s behavioral activity using depth-sensing cameras. Behav Res (2020)”

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT 
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

***************************************************************************************************** */

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QFrame *line;
    QLabel *label;
    QFrame *frame;
    QLabel *label_26;
    QLabel *lblVideo2_5;
    QLabel *lblVideo2;
    QLineEdit *edtFileVideo;
    QPushButton *btnOpenDir;
    QLabel *label_2;
    QFrame *line_2;
    QFrame *frame_8;
    QLabel *label_8;
    QLabel *lblVideo2_6;
    QLabel *lblVideo2_9;
    QRadioButton *rBTrackingMedian;
    QRadioButton *rBTrackingMedianDyn;
    QLabel *lblVideo2_7;
    QRadioButton *rBTrackingGMM;
    QFrame *frame_9;
    QLabel *label_9;
    QPushButton *btnTrackingSTART;
    QProgressBar *pbProgressTrack;
    QPushButton *btnSeeTracking;
    QLabel *lblSeeTracking;
    QFrame *frame_10;
    QLabel *label_10;
    QPushButton *btnOpenDirectoryTracking;
    QLabel *lblSavefile;
    QLabel *lblVideo2_10;
    QLineEdit *edtSaveTrackingData;
    QCheckBox *cbBodyParts;
    QFrame *line_3;
    QLabel *label_3;
    QLabel *label_14;
    QPushButton *btnOpenROI;
    QLabel *lblVideo2_3;
    QFrame *line_4;
    QLabel *label_4;
    QLabel *lblWarningROI;
    QLabel *label_15;
    QLabel *lblWarningTracking;
    QFrame *frame_2;
    QLabel *label_27;
    QTabWidget *tabClassification;
    QWidget *tabTrain;
    QProgressBar *pbProgressClassification;
    QPushButton *btnOpenAnnotatedFile;
    QLabel *lblClassificationStart;
    QLineEdit *edtAnnotatedFile;
    QGroupBox *groupBox_6;
    QCheckBox *cbOptimize;
    QSpinBox *sbKValue;
    QLabel *lblVideo2_12;
    QSpinBox *sbnumberOfClasses;
    QLabel *lblVideo2_22;
    QLabel *lblVideo2_2;
    QPushButton *btnStartClassification;
    QFrame *frame_11;
    QLabel *label_11;
    QWidget *tabTesting;
    QLineEdit *edtAnnotatedFileTesting;
    QLabel *lblVideo2_8;
    QPushButton *btnOpenAnnotatedFileTesting;
    QLabel *lblVideo2_11;
    QPushButton *btnOpenTrainedModel_2;
    QLineEdit *edtTrainedModel_2;
    QFrame *frame_13;
    QLabel *label_13;
    QProgressBar *pbNewClassification_2;
    QPushButton *btnStartTesting;
    QLabel *lblClassificationTesting;
    QWidget *tabClassify;
    QPushButton *btnOpenTrainedModel_3;
    QLineEdit *edtTrainedModel_3;
    QLabel *lblVideo2_4;
    QFrame *frame_12;
    QLabel *label_12;
    QPushButton *btnStartNewClassification;
    QLabel *lblClassificationStart_2;
    QGroupBox *gbParameters;
    QSpinBox *sbROIpixelsX;
    QSpinBox *sbROIpixelsY;
    QLabel *lblVideo2_13;
    QLabel *lblVideo2_14;
    QLabel *lblVideo2_15;
    QSpinBox *sbMinRange;
    QLabel *lblVideo2_16;
    QLabel *lblVideo2_17;
    QLabel *lblVideo2_18;
    QSpinBox *sbMaxRange;
    QLabel *lblVideo2_19;
    QLabel *lblVideo2_20;
    QSpinBox *sbFramesBackModel;
    QCheckBox *cbFullImageX;
    QCheckBox *cbFullImageY;
    QLabel *lblVideo2_21;
    QSpinBox *sbMaxPixelArea;
    QPushButton *btnParameters;
    QLabel *lblTIRAR;
    QCheckBox *cbEPM;
    QCheckBox *cbMultipleVideosForTraining;
    QLabel *label_16;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(562, 749);
        MainWindow->setStyleSheet(QStringLiteral("background-color: rgb(252, 252, 252);"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        line = new QFrame(centralWidget);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(250, 45, 500, 2));
        QSizePolicy sizePolicy(QSizePolicy::Minimum, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(line->sizePolicy().hasHeightForWidth());
        line->setSizePolicy(sizePolicy);
        line->setBaseSize(QSize(0, 0));
        line->setStyleSheet(QStringLiteral("background:rgb(230, 230, 230)"));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 35, 381, 21));
        QFont font;
        font.setFamily(QStringLiteral("Helvetica Neue"));
        font.setPointSize(11);
        font.setBold(true);
        font.setWeight(75);
        label->setFont(font);
        label->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(0, 0, 751, 31));
        QFont font1;
        font1.setFamily(QStringLiteral("Helvetica Neue"));
        font1.setPointSize(16);
        font1.setBold(true);
        font1.setWeight(75);
        frame->setFont(font1);
        frame->setStyleSheet(QStringLiteral("background-color: rgb(0, 85, 127);"));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        label_26 = new QLabel(frame);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(780, -7, 201, 41));
        label_26->setPixmap(QPixmap(QString::fromUtf8("../../../../Downloads/Face3dYN/Face3dYN/Documents/Work/Face3Dyn/ap_face3dyn-11.jpg")));
        label_26->setScaledContents(true);
        lblVideo2_5 = new QLabel(frame);
        lblVideo2_5->setObjectName(QStringLiteral("lblVideo2_5"));
        lblVideo2_5->setGeometry(QRect(10, 0, 501, 31));
        QFont font2;
        font2.setPointSize(12);
        font2.setBold(true);
        font2.setWeight(75);
        lblVideo2_5->setFont(font2);
        lblVideo2_5->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        lblVideo2_5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_5->setWordWrap(true);
        lblVideo2 = new QLabel(centralWidget);
        lblVideo2->setObjectName(QStringLiteral("lblVideo2"));
        lblVideo2->setGeometry(QRect(10, 62, 101, 21));
        QFont font3;
        font3.setPointSize(9);
        font3.setBold(true);
        font3.setWeight(75);
        lblVideo2->setFont(font3);
        lblVideo2->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2->setWordWrap(true);
        edtFileVideo = new QLineEdit(centralWidget);
        edtFileVideo->setObjectName(QStringLiteral("edtFileVideo"));
        edtFileVideo->setEnabled(false);
        edtFileVideo->setGeometry(QRect(116, 64, 231, 20));
        QFont font4;
        font4.setFamily(QStringLiteral("Calibri"));
        edtFileVideo->setFont(font4);
        edtFileVideo->setStyleSheet(QStringLiteral("color: rgb(0, 85, 127);"));
        edtFileVideo->setInputMethodHints(Qt::ImhDigitsOnly);
        edtFileVideo->setAlignment(Qt::AlignCenter);
        btnOpenDir = new QPushButton(centralWidget);
        btnOpenDir->setObjectName(QStringLiteral("btnOpenDir"));
        btnOpenDir->setGeometry(QRect(352, 61, 27, 25));
        QFont font5;
        font5.setFamily(QStringLiteral("Calibri"));
        font5.setPointSize(13);
        font5.setBold(true);
        font5.setWeight(75);
        btnOpenDir->setFont(font5);
        btnOpenDir->setStyleSheet(QLatin1String("background-color:rgb(220, 220, 220);  border-radius:10px;\n"
"color: rgb(84, 84, 84);"));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 99, 351, 21));
        label_2->setFont(font);
        label_2->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        line_2 = new QFrame(centralWidget);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(250, 109, 500, 2));
        sizePolicy.setHeightForWidth(line_2->sizePolicy().hasHeightForWidth());
        line_2->setSizePolicy(sizePolicy);
        line_2->setBaseSize(QSize(0, 0));
        line_2->setStyleSheet(QStringLiteral("background:rgb(230, 230, 230)"));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        frame_8 = new QFrame(centralWidget);
        frame_8->setObjectName(QStringLiteral("frame_8"));
        frame_8->setGeometry(QRect(10, 201, 201, 21));
        QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(frame_8->sizePolicy().hasHeightForWidth());
        frame_8->setSizePolicy(sizePolicy1);
        frame_8->setMinimumSize(QSize(0, 0));
        frame_8->setBaseSize(QSize(0, 0));
        QFont font6;
        font6.setPointSize(11);
        font6.setBold(false);
        font6.setUnderline(false);
        font6.setWeight(50);
        frame_8->setFont(font6);
        frame_8->setStyleSheet(QLatin1String("background-color: rgb(220, 236, 255);\n"
""));
        frame_8->setFrameShape(QFrame::Panel);
        frame_8->setFrameShadow(QFrame::Plain);
        frame_8->setLineWidth(0);
        frame_8->setMidLineWidth(0);
        label_8 = new QLabel(frame_8);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 0, 191, 17));
        QFont font7;
        font7.setFamily(QStringLiteral("Helvetica Neue"));
        font7.setPointSize(9);
        font7.setBold(true);
        font7.setWeight(75);
        label_8->setFont(font7);
        label_8->setStyleSheet(QStringLiteral("color: rgb(85, 85, 85);"));
        lblVideo2_6 = new QLabel(centralWidget);
        lblVideo2_6->setObjectName(QStringLiteral("lblVideo2_6"));
        lblVideo2_6->setGeometry(QRect(30, 250, 171, 16));
        QFont font8;
        font8.setPointSize(7);
        lblVideo2_6->setFont(font8);
        lblVideo2_6->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_6->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_6->setWordWrap(true);
        lblVideo2_9 = new QLabel(centralWidget);
        lblVideo2_9->setObjectName(QStringLiteral("lblVideo2_9"));
        lblVideo2_9->setGeometry(QRect(30, 288, 191, 16));
        lblVideo2_9->setFont(font8);
        lblVideo2_9->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_9->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_9->setWordWrap(true);
        rBTrackingMedian = new QRadioButton(centralWidget);
        rBTrackingMedian->setObjectName(QStringLiteral("rBTrackingMedian"));
        rBTrackingMedian->setGeometry(QRect(9, 235, 191, 19));
        QFont font9;
        font9.setBold(true);
        font9.setWeight(75);
        rBTrackingMedian->setFont(font9);
        rBTrackingMedian->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        rBTrackingMedianDyn = new QRadioButton(centralWidget);
        rBTrackingMedianDyn->setObjectName(QStringLiteral("rBTrackingMedianDyn"));
        rBTrackingMedianDyn->setGeometry(QRect(9, 271, 191, 19));
        rBTrackingMedianDyn->setFont(font9);
        rBTrackingMedianDyn->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        lblVideo2_7 = new QLabel(centralWidget);
        lblVideo2_7->setObjectName(QStringLiteral("lblVideo2_7"));
        lblVideo2_7->setGeometry(QRect(30, 327, 101, 16));
        lblVideo2_7->setFont(font8);
        lblVideo2_7->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_7->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_7->setWordWrap(true);
        rBTrackingGMM = new QRadioButton(centralWidget);
        rBTrackingGMM->setObjectName(QStringLiteral("rBTrackingGMM"));
        rBTrackingGMM->setGeometry(QRect(9, 309, 271, 19));
        QFont font10;
        font10.setPointSize(8);
        font10.setBold(true);
        font10.setItalic(false);
        font10.setWeight(75);
        rBTrackingGMM->setFont(font10);
        rBTrackingGMM->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        frame_9 = new QFrame(centralWidget);
        frame_9->setObjectName(QStringLiteral("frame_9"));
        frame_9->setGeometry(QRect(10, 372, 141, 21));
        sizePolicy1.setHeightForWidth(frame_9->sizePolicy().hasHeightForWidth());
        frame_9->setSizePolicy(sizePolicy1);
        frame_9->setMinimumSize(QSize(0, 0));
        frame_9->setBaseSize(QSize(0, 0));
        frame_9->setFont(font6);
        frame_9->setStyleSheet(QLatin1String("background-color: rgb(220, 236, 255);\n"
""));
        frame_9->setFrameShape(QFrame::Panel);
        frame_9->setFrameShadow(QFrame::Plain);
        frame_9->setLineWidth(0);
        frame_9->setMidLineWidth(0);
        label_9 = new QLabel(frame_9);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(8, 1, 131, 17));
        label_9->setFont(font7);
        label_9->setStyleSheet(QStringLiteral("color: rgb(85, 85, 85);"));
        btnTrackingSTART = new QPushButton(centralWidget);
        btnTrackingSTART->setObjectName(QStringLiteral("btnTrackingSTART"));
        btnTrackingSTART->setGeometry(QRect(159, 372, 80, 21));
        btnTrackingSTART->setFont(font3);
        btnTrackingSTART->setStyleSheet(QLatin1String("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
" border-radius:10px;"));
        pbProgressTrack = new QProgressBar(centralWidget);
        pbProgressTrack->setObjectName(QStringLiteral("pbProgressTrack"));
        pbProgressTrack->setGeometry(QRect(249, 374, 121, 16));
        pbProgressTrack->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        pbProgressTrack->setValue(24);
        btnSeeTracking = new QPushButton(centralWidget);
        btnSeeTracking->setObjectName(QStringLiteral("btnSeeTracking"));
        btnSeeTracking->setGeometry(QRect(330, 370, 43, 25));
        btnSeeTracking->setFont(font3);
        btnSeeTracking->setStyleSheet(QLatin1String("background-color:rgb(220, 220, 220);  border-radius:10px;\n"
"color: rgb(84, 84, 84);"));
        lblSeeTracking = new QLabel(centralWidget);
        lblSeeTracking->setObjectName(QStringLiteral("lblSeeTracking"));
        lblSeeTracking->setGeometry(QRect(243, 371, 81, 21));
        lblSeeTracking->setFont(font3);
        lblSeeTracking->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        lblSeeTracking->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblSeeTracking->setWordWrap(true);
        frame_10 = new QFrame(centralWidget);
        frame_10->setObjectName(QStringLiteral("frame_10"));
        frame_10->setGeometry(QRect(10, 422, 361, 21));
        sizePolicy1.setHeightForWidth(frame_10->sizePolicy().hasHeightForWidth());
        frame_10->setSizePolicy(sizePolicy1);
        frame_10->setMinimumSize(QSize(0, 0));
        frame_10->setBaseSize(QSize(0, 0));
        frame_10->setFont(font6);
        frame_10->setStyleSheet(QLatin1String("background-color: rgb(220, 236, 255);\n"
""));
        frame_10->setFrameShape(QFrame::Panel);
        frame_10->setFrameShadow(QFrame::Plain);
        frame_10->setLineWidth(0);
        frame_10->setMidLineWidth(0);
        label_10 = new QLabel(frame_10);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 2, 341, 17));
        label_10->setFont(font7);
        label_10->setStyleSheet(QStringLiteral("color: rgb(85, 85, 85);"));
        btnOpenDirectoryTracking = new QPushButton(centralWidget);
        btnOpenDirectoryTracking->setObjectName(QStringLiteral("btnOpenDirectoryTracking"));
        btnOpenDirectoryTracking->setGeometry(QRect(308, 478, 27, 25));
        btnOpenDirectoryTracking->setFont(font5);
        btnOpenDirectoryTracking->setStyleSheet(QLatin1String("background-color:rgb(220, 220, 220);  border-radius:10px;\n"
"color: rgb(84, 84, 84);"));
        lblSavefile = new QLabel(centralWidget);
        lblSavefile->setObjectName(QStringLiteral("lblSavefile"));
        lblSavefile->setGeometry(QRect(15, 473, 101, 31));
        lblSavefile->setFont(font3);
        lblSavefile->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblSavefile->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblSavefile->setWordWrap(true);
        lblVideo2_10 = new QLabel(centralWidget);
        lblVideo2_10->setObjectName(QStringLiteral("lblVideo2_10"));
        lblVideo2_10->setGeometry(QRect(14, 446, 111, 31));
        QFont font11;
        font11.setPointSize(8);
        font11.setBold(true);
        font11.setWeight(75);
        lblVideo2_10->setFont(font11);
        lblVideo2_10->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_10->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_10->setWordWrap(true);
        edtSaveTrackingData = new QLineEdit(centralWidget);
        edtSaveTrackingData->setObjectName(QStringLiteral("edtSaveTrackingData"));
        edtSaveTrackingData->setEnabled(false);
        edtSaveTrackingData->setGeometry(QRect(124, 480, 181, 20));
        QFont font12;
        font12.setFamily(QStringLiteral("Calibri"));
        font12.setPointSize(9);
        edtSaveTrackingData->setFont(font12);
        edtSaveTrackingData->setStyleSheet(QStringLiteral("color: rgb(0, 85, 0);"));
        edtSaveTrackingData->setInputMethodHints(Qt::ImhDigitsOnly);
        edtSaveTrackingData->setAlignment(Qt::AlignCenter);
        cbBodyParts = new QCheckBox(centralWidget);
        cbBodyParts->setObjectName(QStringLiteral("cbBodyParts"));
        cbBodyParts->setGeometry(QRect(135, 452, 241, 19));
        QFont font13;
        font13.setPointSize(8);
        cbBodyParts->setFont(font13);
        cbBodyParts->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        line_3 = new QFrame(centralWidget);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(160, 521, 600, 2));
        sizePolicy.setHeightForWidth(line_3->sizePolicy().hasHeightForWidth());
        line_3->setSizePolicy(sizePolicy);
        line_3->setBaseSize(QSize(0, 0));
        line_3->setStyleSheet(QStringLiteral("background:rgb(230, 230, 230)"));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 510, 181, 21));
        label_3->setFont(font);
        label_3->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(440, 707, 111, 20));
        QFont font14;
        font14.setPointSize(10);
        font14.setBold(false);
        font14.setWeight(50);
        label_14->setFont(font14);
        label_14->setStyleSheet(QStringLiteral("color: rgb(0, 85, 127);"));
        label_14->setFrameShape(QFrame::NoFrame);
        label_14->setAlignment(Qt::AlignCenter);
        btnOpenROI = new QPushButton(centralWidget);
        btnOpenROI->setObjectName(QStringLiteral("btnOpenROI"));
        btnOpenROI->setGeometry(QRect(177, 126, 51, 21));
        btnOpenROI->setFont(font3);
        btnOpenROI->setStyleSheet(QLatin1String("background-color: rgb(0, 85, 127);\n"
" border-radius:10px;\n"
"color: rgb(255, 255, 255);"));
        lblVideo2_3 = new QLabel(centralWidget);
        lblVideo2_3->setObjectName(QStringLiteral("lblVideo2_3"));
        lblVideo2_3->setGeometry(QRect(14, 120, 161, 31));
        lblVideo2_3->setFont(font3);
        lblVideo2_3->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_3->setWordWrap(true);
        line_4 = new QFrame(centralWidget);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(250, 172, 500, 2));
        sizePolicy.setHeightForWidth(line_4->sizePolicy().hasHeightForWidth());
        line_4->setSizePolicy(sizePolicy);
        line_4->setBaseSize(QSize(0, 0));
        line_4->setStyleSheet(QStringLiteral("background:rgb(230, 230, 230)"));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 162, 431, 21));
        label_4->setFont(font);
        label_4->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        lblWarningROI = new QLabel(centralWidget);
        lblWarningROI->setObjectName(QStringLiteral("lblWarningROI"));
        lblWarningROI->setGeometry(QRect(236, 129, 171, 16));
        lblWarningROI->setFont(font3);
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(270, 706, 81, 21));
        QFont font15;
        font15.setPointSize(15);
        font15.setBold(true);
        font15.setWeight(75);
        label_15->setFont(font15);
        label_15->setStyleSheet(QStringLiteral("color: rgb(0, 85, 127);"));
        label_15->setFrameShape(QFrame::NoFrame);
        label_15->setAlignment(Qt::AlignCenter);
        lblWarningTracking = new QLabel(centralWidget);
        lblWarningTracking->setObjectName(QStringLiteral("lblWarningTracking"));
        lblWarningTracking->setGeometry(QRect(100, 397, 201, 14));
        lblWarningTracking->setFont(font9);
        lblWarningTracking->setAlignment(Qt::AlignCenter);
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(-22, 730, 791, 21));
        frame_2->setFont(font1);
        frame_2->setStyleSheet(QStringLiteral("background-color: rgb(0, 85, 127);"));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        label_27 = new QLabel(frame_2);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(780, 20, 201, 41));
        label_27->setPixmap(QPixmap(QString::fromUtf8("../../../../Downloads/Face3dYN/Face3dYN/Documents/Work/Face3Dyn/ap_face3dyn-11.jpg")));
        label_27->setScaledContents(true);
        tabClassification = new QTabWidget(centralWidget);
        tabClassification->setObjectName(QStringLiteral("tabClassification"));
        tabClassification->setGeometry(QRect(10, 538, 541, 165));
        tabClassification->setFont(font3);
        tabClassification->setStyleSheet(QStringLiteral("color: rgb(85, 85, 85);"));
        tabTrain = new QWidget();
        tabTrain->setObjectName(QStringLiteral("tabTrain"));
        pbProgressClassification = new QProgressBar(tabTrain);
        pbProgressClassification->setObjectName(QStringLiteral("pbProgressClassification"));
        pbProgressClassification->setGeometry(QRect(228, 77, 121, 16));
        pbProgressClassification->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        pbProgressClassification->setValue(24);
        btnOpenAnnotatedFile = new QPushButton(tabTrain);
        btnOpenAnnotatedFile->setObjectName(QStringLiteral("btnOpenAnnotatedFile"));
        btnOpenAnnotatedFile->setGeometry(QRect(414, 5, 27, 25));
        btnOpenAnnotatedFile->setFont(font5);
        btnOpenAnnotatedFile->setStyleSheet(QLatin1String("background-color:rgb(220, 220, 220);  border-radius:10px;\n"
"color: rgb(84, 84, 84);"));
        lblClassificationStart = new QLabel(tabTrain);
        lblClassificationStart->setObjectName(QStringLiteral("lblClassificationStart"));
        lblClassificationStart->setGeometry(QRect(206, 76, 161, 31));
        lblClassificationStart->setAlignment(Qt::AlignCenter);
        lblClassificationStart->setWordWrap(true);
        edtAnnotatedFile = new QLineEdit(tabTrain);
        edtAnnotatedFile->setObjectName(QStringLiteral("edtAnnotatedFile"));
        edtAnnotatedFile->setEnabled(false);
        edtAnnotatedFile->setGeometry(QRect(228, 7, 181, 20));
        edtAnnotatedFile->setFont(font4);
        edtAnnotatedFile->setInputMethodHints(Qt::ImhDigitsOnly);
        edtAnnotatedFile->setAlignment(Qt::AlignCenter);
        groupBox_6 = new QGroupBox(tabTrain);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(10, 29, 181, 101));
        groupBox_6->setFont(font3);
        groupBox_6->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        cbOptimize = new QCheckBox(groupBox_6);
        cbOptimize->setObjectName(QStringLiteral("cbOptimize"));
        cbOptimize->setGeometry(QRect(6, 50, 171, 19));
        cbOptimize->setFont(font8);
        cbOptimize->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        sbKValue = new QSpinBox(groupBox_6);
        sbKValue->setObjectName(QStringLiteral("sbKValue"));
        sbKValue->setGeometry(QRect(105, 70, 43, 22));
        sbKValue->setMinimum(2);
        sbKValue->setMaximum(20);
        sbKValue->setValue(5);
        lblVideo2_12 = new QLabel(groupBox_6);
        lblVideo2_12->setObjectName(QStringLiteral("lblVideo2_12"));
        lblVideo2_12->setGeometry(QRect(8, 73, 91, 16));
        lblVideo2_12->setFont(font13);
        lblVideo2_12->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_12->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_12->setWordWrap(true);
        sbnumberOfClasses = new QSpinBox(groupBox_6);
        sbnumberOfClasses->setObjectName(QStringLiteral("sbnumberOfClasses"));
        sbnumberOfClasses->setGeometry(QRect(130, 23, 43, 22));
        sbnumberOfClasses->setFont(font3);
        sbnumberOfClasses->setMinimum(2);
        sbnumberOfClasses->setMaximum(100);
        sbnumberOfClasses->setValue(8);
        lblVideo2_22 = new QLabel(groupBox_6);
        lblVideo2_22->setObjectName(QStringLiteral("lblVideo2_22"));
        lblVideo2_22->setGeometry(QRect(8, 24, 121, 16));
        lblVideo2_22->setFont(font3);
        lblVideo2_22->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_22->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_22->setWordWrap(true);
        lblVideo2_2 = new QLabel(tabTrain);
        lblVideo2_2->setObjectName(QStringLiteral("lblVideo2_2"));
        lblVideo2_2->setGeometry(QRect(11, 5, 211, 21));
        lblVideo2_2->setFont(font3);
        lblVideo2_2->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_2->setWordWrap(true);
        btnStartClassification = new QPushButton(tabTrain);
        btnStartClassification->setObjectName(QStringLiteral("btnStartClassification"));
        btnStartClassification->setGeometry(QRect(383, 48, 61, 21));
        btnStartClassification->setFont(font3);
        btnStartClassification->setStyleSheet(QLatin1String("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
" border-radius:10px;"));
        frame_11 = new QFrame(tabTrain);
        frame_11->setObjectName(QStringLiteral("frame_11"));
        frame_11->setGeometry(QRect(203, 49, 171, 21));
        sizePolicy1.setHeightForWidth(frame_11->sizePolicy().hasHeightForWidth());
        frame_11->setSizePolicy(sizePolicy1);
        frame_11->setMinimumSize(QSize(0, 0));
        frame_11->setBaseSize(QSize(0, 0));
        frame_11->setFont(font6);
        frame_11->setStyleSheet(QLatin1String("background-color: rgb(220, 236, 255);\n"
""));
        frame_11->setFrameShape(QFrame::Panel);
        frame_11->setFrameShadow(QFrame::Plain);
        frame_11->setLineWidth(0);
        frame_11->setMidLineWidth(0);
        label_11 = new QLabel(frame_11);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(7, 1, 161, 17));
        label_11->setFont(font7);
        label_11->setStyleSheet(QStringLiteral("color: rgb(85, 85, 85);"));
        tabClassification->addTab(tabTrain, QString());
        btnOpenAnnotatedFile->raise();
        lblClassificationStart->raise();
        edtAnnotatedFile->raise();
        groupBox_6->raise();
        lblVideo2_2->raise();
        btnStartClassification->raise();
        frame_11->raise();
        pbProgressClassification->raise();
        tabTesting = new QWidget();
        tabTesting->setObjectName(QStringLiteral("tabTesting"));
        edtAnnotatedFileTesting = new QLineEdit(tabTesting);
        edtAnnotatedFileTesting->setObjectName(QStringLiteral("edtAnnotatedFileTesting"));
        edtAnnotatedFileTesting->setEnabled(false);
        edtAnnotatedFileTesting->setGeometry(QRect(224, 12, 181, 20));
        edtAnnotatedFileTesting->setFont(font4);
        edtAnnotatedFileTesting->setInputMethodHints(Qt::ImhDigitsOnly);
        edtAnnotatedFileTesting->setAlignment(Qt::AlignCenter);
        lblVideo2_8 = new QLabel(tabTesting);
        lblVideo2_8->setObjectName(QStringLiteral("lblVideo2_8"));
        lblVideo2_8->setGeometry(QRect(7, 10, 211, 21));
        lblVideo2_8->setFont(font3);
        lblVideo2_8->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_8->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_8->setWordWrap(true);
        btnOpenAnnotatedFileTesting = new QPushButton(tabTesting);
        btnOpenAnnotatedFileTesting->setObjectName(QStringLiteral("btnOpenAnnotatedFileTesting"));
        btnOpenAnnotatedFileTesting->setGeometry(QRect(410, 10, 27, 25));
        btnOpenAnnotatedFileTesting->setFont(font5);
        btnOpenAnnotatedFileTesting->setStyleSheet(QLatin1String("background-color:rgb(220, 220, 220);  border-radius:10px;\n"
"color: rgb(84, 84, 84);"));
        lblVideo2_11 = new QLabel(tabTesting);
        lblVideo2_11->setObjectName(QStringLiteral("lblVideo2_11"));
        lblVideo2_11->setGeometry(QRect(8, 38, 191, 21));
        lblVideo2_11->setFont(font3);
        lblVideo2_11->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_11->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_11->setWordWrap(true);
        btnOpenTrainedModel_2 = new QPushButton(tabTesting);
        btnOpenTrainedModel_2->setObjectName(QStringLiteral("btnOpenTrainedModel_2"));
        btnOpenTrainedModel_2->setGeometry(QRect(410, 38, 27, 25));
        btnOpenTrainedModel_2->setFont(font5);
        btnOpenTrainedModel_2->setStyleSheet(QLatin1String("background-color:rgb(220, 220, 220);  border-radius:10px;\n"
"color: rgb(84, 84, 84);"));
        edtTrainedModel_2 = new QLineEdit(tabTesting);
        edtTrainedModel_2->setObjectName(QStringLiteral("edtTrainedModel_2"));
        edtTrainedModel_2->setEnabled(false);
        edtTrainedModel_2->setGeometry(QRect(224, 40, 181, 20));
        edtTrainedModel_2->setFont(font4);
        edtTrainedModel_2->setInputMethodHints(Qt::ImhDigitsOnly);
        edtTrainedModel_2->setAlignment(Qt::AlignCenter);
        frame_13 = new QFrame(tabTesting);
        frame_13->setObjectName(QStringLiteral("frame_13"));
        frame_13->setGeometry(QRect(6, 75, 131, 21));
        sizePolicy1.setHeightForWidth(frame_13->sizePolicy().hasHeightForWidth());
        frame_13->setSizePolicy(sizePolicy1);
        frame_13->setMinimumSize(QSize(0, 0));
        frame_13->setBaseSize(QSize(0, 0));
        frame_13->setFont(font6);
        frame_13->setStyleSheet(QLatin1String("background-color: rgb(220, 236, 255);\n"
""));
        frame_13->setFrameShape(QFrame::Panel);
        frame_13->setFrameShadow(QFrame::Plain);
        frame_13->setLineWidth(0);
        frame_13->setMidLineWidth(0);
        label_13 = new QLabel(frame_13);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(7, 2, 131, 17));
        label_13->setFont(font7);
        label_13->setStyleSheet(QStringLiteral("color: rgb(85, 85, 85);"));
        pbNewClassification_2 = new QProgressBar(tabTesting);
        pbNewClassification_2->setObjectName(QStringLiteral("pbNewClassification_2"));
        pbNewClassification_2->setGeometry(QRect(216, 77, 121, 16));
        pbNewClassification_2->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        pbNewClassification_2->setValue(24);
        btnStartTesting = new QPushButton(tabTesting);
        btnStartTesting->setObjectName(QStringLiteral("btnStartTesting"));
        btnStartTesting->setGeometry(QRect(146, 75, 61, 21));
        btnStartTesting->setFont(font3);
        btnStartTesting->setStyleSheet(QLatin1String("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
" border-radius:10px;"));
        lblClassificationTesting = new QLabel(tabTesting);
        lblClassificationTesting->setObjectName(QStringLiteral("lblClassificationTesting"));
        lblClassificationTesting->setGeometry(QRect(212, 71, 161, 31));
        lblClassificationTesting->setAlignment(Qt::AlignCenter);
        lblClassificationTesting->setWordWrap(true);
        tabClassification->addTab(tabTesting, QString());
        tabClassify = new QWidget();
        tabClassify->setObjectName(QStringLiteral("tabClassify"));
        btnOpenTrainedModel_3 = new QPushButton(tabClassify);
        btnOpenTrainedModel_3->setObjectName(QStringLiteral("btnOpenTrainedModel_3"));
        btnOpenTrainedModel_3->setGeometry(QRect(394, 10, 27, 25));
        btnOpenTrainedModel_3->setFont(font5);
        btnOpenTrainedModel_3->setStyleSheet(QLatin1String("background-color:rgb(220, 220, 220);  border-radius:10px;\n"
"color: rgb(84, 84, 84);"));
        edtTrainedModel_3 = new QLineEdit(tabClassify);
        edtTrainedModel_3->setObjectName(QStringLiteral("edtTrainedModel_3"));
        edtTrainedModel_3->setEnabled(false);
        edtTrainedModel_3->setGeometry(QRect(208, 12, 181, 20));
        edtTrainedModel_3->setFont(font4);
        edtTrainedModel_3->setInputMethodHints(Qt::ImhDigitsOnly);
        edtTrainedModel_3->setAlignment(Qt::AlignCenter);
        lblVideo2_4 = new QLabel(tabClassify);
        lblVideo2_4->setObjectName(QStringLiteral("lblVideo2_4"));
        lblVideo2_4->setGeometry(QRect(10, 10, 191, 21));
        lblVideo2_4->setFont(font3);
        lblVideo2_4->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_4->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_4->setWordWrap(true);
        frame_12 = new QFrame(tabClassify);
        frame_12->setObjectName(QStringLiteral("frame_12"));
        frame_12->setGeometry(QRect(10, 51, 131, 21));
        sizePolicy1.setHeightForWidth(frame_12->sizePolicy().hasHeightForWidth());
        frame_12->setSizePolicy(sizePolicy1);
        frame_12->setMinimumSize(QSize(0, 0));
        frame_12->setBaseSize(QSize(0, 0));
        frame_12->setFont(font6);
        frame_12->setStyleSheet(QLatin1String("background-color: rgb(220, 236, 255);\n"
""));
        frame_12->setFrameShape(QFrame::Panel);
        frame_12->setFrameShadow(QFrame::Plain);
        frame_12->setLineWidth(0);
        frame_12->setMidLineWidth(0);
        label_12 = new QLabel(frame_12);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(7, 2, 131, 17));
        label_12->setFont(font7);
        label_12->setStyleSheet(QStringLiteral("color: rgb(85, 85, 85);"));
        btnStartNewClassification = new QPushButton(tabClassify);
        btnStartNewClassification->setObjectName(QStringLiteral("btnStartNewClassification"));
        btnStartNewClassification->setGeometry(QRect(150, 51, 61, 21));
        btnStartNewClassification->setFont(font3);
        btnStartNewClassification->setStyleSheet(QLatin1String("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
" border-radius:10px;"));
        lblClassificationStart_2 = new QLabel(tabClassify);
        lblClassificationStart_2->setObjectName(QStringLiteral("lblClassificationStart_2"));
        lblClassificationStart_2->setGeometry(QRect(214, 49, 161, 31));
        lblClassificationStart_2->setAlignment(Qt::AlignCenter);
        lblClassificationStart_2->setWordWrap(true);
        tabClassification->addTab(tabClassify, QString());
        lblClassificationStart_2->raise();
        btnOpenTrainedModel_3->raise();
        edtTrainedModel_3->raise();
        lblVideo2_4->raise();
        frame_12->raise();
        btnStartNewClassification->raise();
        gbParameters = new QGroupBox(centralWidget);
        gbParameters->setObjectName(QStringLiteral("gbParameters"));
        gbParameters->setGeometry(QRect(291, 190, 251, 173));
        gbParameters->setFont(font11);
        gbParameters->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        sbROIpixelsX = new QSpinBox(gbParameters);
        sbROIpixelsX->setObjectName(QStringLiteral("sbROIpixelsX"));
        sbROIpixelsX->setGeometry(QRect(141, 22, 43, 22));
        sbROIpixelsX->setFont(font8);
        sbROIpixelsX->setMaximum(100);
        sbROIpixelsX->setSingleStep(10);
        sbROIpixelsX->setValue(60);
        sbROIpixelsY = new QSpinBox(gbParameters);
        sbROIpixelsY->setObjectName(QStringLiteral("sbROIpixelsY"));
        sbROIpixelsY->setGeometry(QRect(141, 44, 43, 22));
        sbROIpixelsY->setFont(font8);
        sbROIpixelsY->setMaximum(100);
        sbROIpixelsY->setSingleStep(10);
        sbROIpixelsY->setValue(30);
        lblVideo2_13 = new QLabel(gbParameters);
        lblVideo2_13->setObjectName(QStringLiteral("lblVideo2_13"));
        lblVideo2_13->setGeometry(QRect(10, 24, 41, 16));
        QFont font16;
        font16.setPointSize(7);
        font16.setBold(true);
        font16.setWeight(75);
        lblVideo2_13->setFont(font16);
        lblVideo2_13->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_13->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_13->setWordWrap(true);
        lblVideo2_14 = new QLabel(gbParameters);
        lblVideo2_14->setObjectName(QStringLiteral("lblVideo2_14"));
        lblVideo2_14->setGeometry(QRect(52, 24, 101, 16));
        lblVideo2_14->setFont(font8);
        lblVideo2_14->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_14->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_14->setWordWrap(true);
        lblVideo2_15 = new QLabel(gbParameters);
        lblVideo2_15->setObjectName(QStringLiteral("lblVideo2_15"));
        lblVideo2_15->setGeometry(QRect(51, 46, 101, 16));
        lblVideo2_15->setFont(font8);
        lblVideo2_15->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_15->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_15->setWordWrap(true);
        sbMinRange = new QSpinBox(gbParameters);
        sbMinRange->setObjectName(QStringLiteral("sbMinRange"));
        sbMinRange->setGeometry(QRect(167, 68, 43, 22));
        sbMinRange->setFont(font8);
        sbMinRange->setMaximum(10);
        sbMinRange->setValue(5);
        lblVideo2_16 = new QLabel(gbParameters);
        lblVideo2_16->setObjectName(QStringLiteral("lblVideo2_16"));
        lblVideo2_16->setGeometry(QRect(9, 68, 121, 16));
        lblVideo2_16->setFont(font16);
        lblVideo2_16->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_16->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_16->setWordWrap(true);
        lblVideo2_17 = new QLabel(gbParameters);
        lblVideo2_17->setObjectName(QStringLiteral("lblVideo2_17"));
        lblVideo2_17->setGeometry(QRect(117, 69, 61, 16));
        lblVideo2_17->setFont(font8);
        lblVideo2_17->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_17->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_17->setWordWrap(true);
        lblVideo2_18 = new QLabel(gbParameters);
        lblVideo2_18->setObjectName(QStringLiteral("lblVideo2_18"));
        lblVideo2_18->setGeometry(QRect(115, 90, 61, 16));
        lblVideo2_18->setFont(font8);
        lblVideo2_18->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_18->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_18->setWordWrap(true);
        sbMaxRange = new QSpinBox(gbParameters);
        sbMaxRange->setObjectName(QStringLiteral("sbMaxRange"));
        sbMaxRange->setGeometry(QRect(167, 90, 43, 22));
        sbMaxRange->setFont(font8);
        sbMaxRange->setMinimum(10);
        sbMaxRange->setMaximum(1000);
        sbMaxRange->setSingleStep(10);
        sbMaxRange->setValue(300);
        lblVideo2_19 = new QLabel(gbParameters);
        lblVideo2_19->setObjectName(QStringLiteral("lblVideo2_19"));
        lblVideo2_19->setGeometry(QRect(10, 108, 161, 16));
        lblVideo2_19->setFont(font16);
        lblVideo2_19->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_19->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_19->setWordWrap(true);
        lblVideo2_20 = new QLabel(gbParameters);
        lblVideo2_20->setObjectName(QStringLiteral("lblVideo2_20"));
        lblVideo2_20->setGeometry(QRect(47, 124, 61, 16));
        lblVideo2_20->setFont(font8);
        lblVideo2_20->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_20->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_20->setWordWrap(true);
        sbFramesBackModel = new QSpinBox(gbParameters);
        sbFramesBackModel->setObjectName(QStringLiteral("sbFramesBackModel"));
        sbFramesBackModel->setGeometry(QRect(91, 124, 43, 22));
        sbFramesBackModel->setFont(font8);
        sbFramesBackModel->setMinimum(100);
        sbFramesBackModel->setMaximum(500);
        sbFramesBackModel->setSingleStep(10);
        sbFramesBackModel->setValue(300);
        cbFullImageX = new QCheckBox(gbParameters);
        cbFullImageX->setObjectName(QStringLiteral("cbFullImageX"));
        cbFullImageX->setGeometry(QRect(188, 24, 61, 19));
        cbFullImageX->setFont(font8);
        cbFullImageY = new QCheckBox(gbParameters);
        cbFullImageY->setObjectName(QStringLiteral("cbFullImageY"));
        cbFullImageY->setGeometry(QRect(188, 46, 61, 19));
        cbFullImageY->setFont(font8);
        lblVideo2_21 = new QLabel(gbParameters);
        lblVideo2_21->setObjectName(QStringLiteral("lblVideo2_21"));
        lblVideo2_21->setGeometry(QRect(10, 150, 161, 16));
        lblVideo2_21->setFont(font16);
        lblVideo2_21->setStyleSheet(QStringLiteral("color: rgb(83, 83, 83);"));
        lblVideo2_21->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lblVideo2_21->setWordWrap(true);
        sbMaxPixelArea = new QSpinBox(gbParameters);
        sbMaxPixelArea->setObjectName(QStringLiteral("sbMaxPixelArea"));
        sbMaxPixelArea->setGeometry(QRect(174, 147, 51, 22));
        sbMaxPixelArea->setFont(font8);
        sbMaxPixelArea->setMinimum(1500);
        sbMaxPixelArea->setMaximum(3500);
        sbMaxPixelArea->setSingleStep(100);
        sbMaxPixelArea->setValue(1500);
        lblVideo2_13->raise();
        lblVideo2_14->raise();
        lblVideo2_15->raise();
        lblVideo2_16->raise();
        lblVideo2_17->raise();
        sbMinRange->raise();
        lblVideo2_18->raise();
        sbROIpixelsX->raise();
        sbROIpixelsY->raise();
        lblVideo2_19->raise();
        lblVideo2_20->raise();
        sbFramesBackModel->raise();
        sbMaxRange->raise();
        cbFullImageX->raise();
        cbFullImageY->raise();
        lblVideo2_21->raise();
        sbMaxPixelArea->raise();
        btnParameters = new QPushButton(centralWidget);
        btnParameters->setObjectName(QStringLiteral("btnParameters"));
        btnParameters->setGeometry(QRect(290, 188, 251, 21));
        btnParameters->setFont(font9);
        btnParameters->setStyleSheet(QLatin1String("background-color:rgb(220, 220, 220);  border-radius:10px;\n"
"color: rgb(84, 84, 84);"));
        lblTIRAR = new QLabel(centralWidget);
        lblTIRAR->setObjectName(QStringLiteral("lblTIRAR"));
        lblTIRAR->setGeometry(QRect(380, 366, 171, 31));
        lblTIRAR->setFont(font3);
        lblTIRAR->setStyleSheet(QStringLiteral("color: rgb(139, 6, 6);"));
        lblTIRAR->setFrameShape(QFrame::NoFrame);
        lblTIRAR->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        cbEPM = new QCheckBox(centralWidget);
        cbEPM->setObjectName(QStringLiteral("cbEPM"));
        cbEPM->setGeometry(QRect(199, 236, 51, 19));
        cbEPM->setStyleSheet(QStringLiteral("color: rgb(139, 6, 6);"));
        cbMultipleVideosForTraining = new QCheckBox(centralWidget);
        cbMultipleVideosForTraining->setObjectName(QStringLiteral("cbMultipleVideosForTraining"));
        cbMultipleVideosForTraining->setGeometry(QRect(387, 64, 151, 19));
        cbMultipleVideosForTraining->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(348, 707, 81, 21));
        QFont font17;
        font17.setPointSize(13);
        font17.setBold(false);
        font17.setWeight(50);
        label_16->setFont(font17);
        label_16->setStyleSheet(QStringLiteral("color: rgb(0, 85, 127);"));
        label_16->setFrameShape(QFrame::NoFrame);
        label_16->setAlignment(Qt::AlignCenter);
        MainWindow->setCentralWidget(centralWidget);
        gbParameters->raise();
        line_2->raise();
        line->raise();
        label->raise();
        frame->raise();
        lblVideo2->raise();
        edtFileVideo->raise();
        btnOpenDir->raise();
        label_2->raise();
        frame_8->raise();
        lblVideo2_6->raise();
        lblVideo2_9->raise();
        rBTrackingMedian->raise();
        rBTrackingMedianDyn->raise();
        lblVideo2_7->raise();
        rBTrackingGMM->raise();
        frame_9->raise();
        btnTrackingSTART->raise();
        btnSeeTracking->raise();
        lblSeeTracking->raise();
        frame_10->raise();
        btnOpenDirectoryTracking->raise();
        lblSavefile->raise();
        lblVideo2_10->raise();
        edtSaveTrackingData->raise();
        cbBodyParts->raise();
        line_3->raise();
        label_3->raise();
        btnOpenROI->raise();
        lblVideo2_3->raise();
        line_4->raise();
        label_4->raise();
        lblWarningROI->raise();
        label_15->raise();
        label_14->raise();
        lblWarningTracking->raise();
        frame_2->raise();
        pbProgressTrack->raise();
        tabClassification->raise();
        btnParameters->raise();
        lblTIRAR->raise();
        cbEPM->raise();
        cbMultipleVideosForTraining->raise();
        label_16->raise();

        retranslateUi(MainWindow);

        tabClassification->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "CaT-z : 3D TRACKING AND BEHAVIOR CLASSIFICATION GUI", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "Files' Selection: RGB and depth frames (.png files)", Q_NULLPTR));
        label_26->setText(QString());
        lblVideo2_5->setText(QApplication::translate("MainWindow", "3D TRACKING AND BEHAVIOR CLASSIFICATION GUI", Q_NULLPTR));
        lblVideo2->setText(QApplication::translate("MainWindow", "Select directory:", Q_NULLPTR));
        btnOpenDir->setText(QApplication::translate("MainWindow", "...", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "Region of interest - tracking and classification", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "Select segmentation method:", Q_NULLPTR));
        lblVideo2_6->setText(QApplication::translate("MainWindow", "Static background: 300-frames' median", Q_NULLPTR));
        lblVideo2_9->setText(QApplication::translate("MainWindow", "Adaptive background & 100-frames' median", Q_NULLPTR));
        rBTrackingMedian->setText(QApplication::translate("MainWindow", "Median-difference approach", Q_NULLPTR));
        rBTrackingMedianDyn->setText(QApplication::translate("MainWindow", "Median-dynamic approach", Q_NULLPTR));
        lblVideo2_7->setText(QApplication::translate("MainWindow", "Adaptive background", Q_NULLPTR));
        rBTrackingGMM->setText(QApplication::translate("MainWindow", "Modified Gaussian Mixture Model approach", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "Start segmentation:", Q_NULLPTR));
        btnTrackingSTART->setText(QApplication::translate("MainWindow", "START", Q_NULLPTR));
        btnSeeTracking->setText(QApplication::translate("MainWindow", "PLAY", Q_NULLPTR));
        lblSeeTracking->setText(QApplication::translate("MainWindow", "See tracking:", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "Save tracking data - centroid & body parts (if selected):", Q_NULLPTR));
        btnOpenDirectoryTracking->setText(QApplication::translate("MainWindow", "...", Q_NULLPTR));
        lblSavefile->setText(QApplication::translate("MainWindow", "Save to .csv file:", Q_NULLPTR));
        lblVideo2_10->setText(QApplication::translate("MainWindow", "Select (optional)):", Q_NULLPTR));
        cbBodyParts->setText(QApplication::translate("MainWindow", "Body Parts (nose, head and tail coordinates)", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "Behavior Classification", Q_NULLPTR));
        label_14->setText(QApplication::translate("MainWindow", " by AG & PA. 2017", Q_NULLPTR));
        btnOpenROI->setText(QApplication::translate("MainWindow", "ROI", Q_NULLPTR));
        lblVideo2_3->setText(QApplication::translate("MainWindow", "Select region of interest:", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "Segmentation & Tracking - WHOLE-BODY + BODY PARTS", Q_NULLPTR));
        lblWarningROI->setText(QString());
        label_15->setText(QApplication::translate("MainWindow", "CaT - z", Q_NULLPTR));
        lblWarningTracking->setText(QString());
        label_27->setText(QString());
        btnOpenAnnotatedFile->setText(QApplication::translate("MainWindow", "...", Q_NULLPTR));
        lblClassificationStart->setText(QString());
        groupBox_6->setTitle(QApplication::translate("MainWindow", "Classification options", Q_NULLPTR));
        cbOptimize->setText(QApplication::translate("MainWindow", "Optimize C and gamma parameters", Q_NULLPTR));
        lblVideo2_12->setText(QApplication::translate("MainWindow", "Number of folds: k", Q_NULLPTR));
        lblVideo2_22->setText(QApplication::translate("MainWindow", "Number of classes:", Q_NULLPTR));
        lblVideo2_2->setText(QApplication::translate("MainWindow", "Select file with annotated frames:", Q_NULLPTR));
        btnStartClassification->setText(QApplication::translate("MainWindow", "START", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "Train classification model:", Q_NULLPTR));
        tabClassification->setTabText(tabClassification->indexOf(tabTrain), QApplication::translate("MainWindow", "Training", Q_NULLPTR));
        lblVideo2_8->setText(QApplication::translate("MainWindow", "Select file with annotated frames:", Q_NULLPTR));
        btnOpenAnnotatedFileTesting->setText(QApplication::translate("MainWindow", "...", Q_NULLPTR));
        lblVideo2_11->setText(QApplication::translate("MainWindow", "Select file with trained model:", Q_NULLPTR));
        btnOpenTrainedModel_2->setText(QApplication::translate("MainWindow", "...", Q_NULLPTR));
        edtTrainedModel_2->setText(QString());
#ifndef QT_NO_TOOLTIP
        label_13->setToolTip(QApplication::translate("MainWindow", "Test new video, calculating accuracy and confusion matrix of the trained model", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
        label_13->setText(QApplication::translate("MainWindow", "Test new video:", Q_NULLPTR));
        btnStartTesting->setText(QApplication::translate("MainWindow", "START", Q_NULLPTR));
        lblClassificationTesting->setText(QString());
        tabClassification->setTabText(tabClassification->indexOf(tabTesting), QApplication::translate("MainWindow", "Testing", Q_NULLPTR));
        btnOpenTrainedModel_3->setText(QApplication::translate("MainWindow", "...", Q_NULLPTR));
        edtTrainedModel_3->setText(QString());
        lblVideo2_4->setText(QApplication::translate("MainWindow", "Select file with trained model:", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "Classify new video:", Q_NULLPTR));
        btnStartNewClassification->setText(QApplication::translate("MainWindow", "START", Q_NULLPTR));
        lblClassificationStart_2->setText(QString());
        tabClassification->setTabText(tabClassification->indexOf(tabClassify), QApplication::translate("MainWindow", "Classification", Q_NULLPTR));
        gbParameters->setTitle(QString());
        lblVideo2_13->setText(QApplication::translate("MainWindow", "Border:", Q_NULLPTR));
        lblVideo2_14->setText(QApplication::translate("MainWindow", "Number of pixels (x):", Q_NULLPTR));
        lblVideo2_15->setText(QApplication::translate("MainWindow", "Number of pixels (y):", Q_NULLPTR));
        lblVideo2_16->setText(QApplication::translate("MainWindow", "Depth errors' range:", Q_NULLPTR));
        lblVideo2_17->setText(QApplication::translate("MainWindow", "min [mm]:", Q_NULLPTR));
        lblVideo2_18->setText(QApplication::translate("MainWindow", "max [mm]:", Q_NULLPTR));
        lblVideo2_19->setText(QApplication::translate("MainWindow", "Background model estimation:", Q_NULLPTR));
        lblVideo2_20->setText(QApplication::translate("MainWindow", "# frames:", Q_NULLPTR));
        cbFullImageX->setText(QApplication::translate("MainWindow", "full image", Q_NULLPTR));
        cbFullImageY->setText(QApplication::translate("MainWindow", "full image", Q_NULLPTR));
        lblVideo2_21->setText(QApplication::translate("MainWindow", "Animal's maximum area [pixel]:", Q_NULLPTR));
        btnParameters->setText(QApplication::translate("MainWindow", "Segmentation parameters (optional)", Q_NULLPTR));
        lblTIRAR->setText(QApplication::translate("MainWindow", "Segmentation...", Q_NULLPTR));
        cbEPM->setText(QApplication::translate("MainWindow", "EPM", Q_NULLPTR));
        cbMultipleVideosForTraining->setText(QApplication::translate("MainWindow", "Multiple videos for training", Q_NULLPTR));
        label_16->setText(QApplication::translate("MainWindow", "software", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
